spring:
  application:
    name: "CultureMate API"
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: create-drop # 개발시 update, 운영시 validate, 테스트시 create or create-drop
    properties:
      hibernate:
       show_sql: true
      format_sql: true
logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.orm.jdbc.bind: trace