# 공통 설정 (모든 프로파일에서 공유)
spring:
  application:
    name: "CultureMate API"

  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 500MB

# JWT 설정
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

# 이미지 업로드 경로
custom:
  path:
    upload:
      default: src/main/resources/static/images
  swagger:
    server-url: http://localhost:8080
    server-description: 개발 서버

# CORS 설정 (프로파일별로 오버라이드 가능)
cors:
  allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS,HEAD
  allowed-headers: "Content-Type,Authorization,X-Requested-With,Accept,Accept-Language,Origin"
  allow-credentials: true
  max-age: 3600

# OpenAPI/Swagger 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none
